image: python:3.12

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

cache:
  paths:
    - .pip-cache/
    - venv/

stages:
  - test

test:
  stage: test
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.8", "3.9", "3.10"]
  image: python:$PYTHON_VERSION
  before_script:
    - python -m pip install --upgrade pip
    - pip install -e .
    - pip install pytest pytest-cov flake8
  script:
    - flake8 src tests --count --select=E9,F63,F7,F82 --show-source --statistics
    - flake8 src tests --count --max-complexity=10 --max-line-length=127 --statistics
    - pytest tests/ --cov=src --cov-report=xml
  coverage: '/TOTAL.+ ([0-9]{1,3}%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml